### ISSUE TITLE
Boolean not supported in resource generator

### ISSUE THREAD

**Issue by peterhartman** [ash-project/ash_json_api_wrapper#1]
The resource generator doesn't support boolean properties.

```elixir
%{"type" => "boolean"} ->
    ":boolean"
``` 

is needed around

https://github.com/ash-project/ash_json_api_wrapper/blob/418de7a1bd187adc0e95bb4f8f43891f511f6285/lib/open_api/resource_generator.ex#L90

**Comment by peterhartman** [comment]
Sure. As you can see, I have created a fork with that intention. Unfortunately I got stuck trying to create a failing test for this issue. I am going down the line of adding a new test based on https://petstore.swagger.io/#/store/getOrderById as Cybrid doesn't seem to have any boolean parameters. 

Unfortunately the API that I discovered this issue against is not public yet.

It will take me some time to learn enough about this library (and Ash and Elixir) to build the failing test (what better way to learn!). I won't be offended if someone ends up fixing it before I get there though.

**Comment by zachdaniel** [comment]
👍 sounds good!

**Comment by peterhartman** [comment]
I was inspired to give it another try. The test passes with my fix and fails without so that is something at least 🤷

**Comment by zachdaniel** [comment]
Closed in https://github.com/ash-project/ash_json_api_wrapper/pull/2
